import type {Metadata} from "next";
import React from "react";
import {SidebarProvider} from "@/components/ui/sidebar";
import {LeftPanel} from '@/components/left-panel';
import "./globals.css";


export const metadata: Metadata = {
    title: "llmManus",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="zh-CN">
        <body>
        <SidebarProvider
            style={{
                // eslint-disable-next-line @typescript-eslint/ban-ts-comment
                // @ts-expect-error
                '--sidebar-width': '300px',
                '--sidebar-width-icon': '300px',
            }}
        >
            {/* 左侧的面板 */}
            <LeftPanel></LeftPanel>
            {/* 右侧的内容 */}
            <div className="flex-1 bg-[#f8f8f7]">
                {children}
            </div>
        </SidebarProvider>
        </body>
        </html>
    );
}
